captainVersion: 4
services:
    # anything-llm
    $$cap_appname:
        image: mintplexlabs/anythingllm:$$cap_llm_version
        environment:
            UID: $$cap_uid
            GID: $$cap_gid
            GENERATE_SOURCEMAP: 'false'
            DISABLE_TELEMETRY: 'true'
            VITE_API_BASE: http://srv-captain--$$cap_appname:3001/api
            STORAGE_DIR: /app/server/storage
        volumes:
            - $$cap_appname-server:/app/server/
            - $$cap_appname-storage:/app/server/storage
            - $$cap_appname-hotdir:/app/server/hotdir
            - $$cap_appname-outputs:/app/server/outputs
        caproverExtra:
            containerHttpPort: 3001
caproverOneClickApp:
    variables:
        - id: $$cap_llm_version
          label: Anythingllm Version
          defaultValue: '1.8.5'
          description: Checkout their docker page for the valid tags https://hub.docker.com/r/mintplexlabs/anythingllm/tags

        - id: $$cap_uid
          label: User ID
          defaultValue: '1000'
          description: User ID that the process uses, run (id $user) in your instance to see the id
          validRegex: /.{1,}/

        - id: $$cap_gid
          label: Group ID
          defaultValue: '1000'
          description: Group ID that the process uses, run (id $user) in your instance to see the id
          validRegex: /.{1,}/
    instructions:
        start: >-
            A multi-user ChatGPT for any LLMs, and vector database. Unlimited documents, messages, and storage in one privacy-focused app. Now available as a desktop application!
        end: >-
            Aaaand you're done! 😄
            Your service is available at http://$$cap_appname.$$cap_root_domain
    displayName: 'AnythingLLM'
    isOfficial: true
    baseUrl: https://github.com/Mintplex-Labs/anything-llm
    description: AnythingLLM A private ChatGPT to chat with anything!.
    documentation: Taken from https://github.com/Mintplex-Labs/anything-llm
