captainVersion: 4
services:
    # Jellyseerr
    $$cap_appname:
        image: fallenbagel/jellyseerr:$$cap_jellyseerr_version
        environment:
            TZ: $$cap_tz
        caproverExtra:
            containerHttpPort: 5055
caproverOneClickApp:
    variables:
        - id: $$cap_jellyseerr_version
          label: Jellyseerr Version
          defaultValue: '1.7.0'
          description: Checkout their docker page for the valid tags https://hub.docker.com/r/fallenbagel/jellyseerr/tags
          validRegex: /^([^\s^\/])+$/

        - id: $$cap_tz
          label: Time Zone
          defaultValue: Asia/Istanbul
          description: Set the timezone. Get yours from https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
          validRegex: /.{1,}/
    instructions:
        start: |-
            **Jellyseerr** is a free and open source fork of Overseerr for managing requests for your media library. It integrates with your existing services, such as Sonarr, Radarr, and Jellyfin!
        end: |-
            ✅ Jellyseerr has been deployed!
            --------------------------------------------
            ❗️ **IMPORTANT**:
            _*On Jellyfin, ensure the `settings > Home > Automatically group content from the following folders into views such as 'Movies', 'Music' and 'TV'` is turned off*_
    displayName: Jellyseerr
    isOfficial: true
    baseUrl: https://github.com/Fallenbagel/jellyseerr
    description: Fork of overseerr for jellyfin support
    documentation: Taken from https://github.com/Fallenbagel/jellyseerr
