captainVersion: 4
services:
    $$cap_appname:
        image: linuxserver/librespeed:$$cap_librespeed_version
        restart: always
        environment:
            TZ: $$cap_tz
            PUID: $$cap_puid
            PGID: $$cap_guid
            PASSWORD: $$cap_password
        ports:
            - $$cap_webui_port:80
        volumes:
            - $$cap_appname-config:/config
        caproverExtra:
            containerHttpPort: '80'
caproverOneClickApp:
    variables:
        - id: $$cap_tz
          label: Timezone
          description: This is the timezone for the application, find yours at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
          defaultValue: Europe/Brussels
        - id: $$cap_librespeed_version
          label: librespeed Version
          defaultValue: 'latest'
          description: Checkout their docker page for the valid tags https://hub.docker.com/r/linuxserver/librespeed/tags
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_puid
          label: User ID
          defaultValue: '1000'
          description: User ID that the process uses, run (id $user) in your instance to see the id
          validRegex: /.{1,}/
        - id: $$cap_guid
          label: Group ID
          defaultValue: '1000'
          description: Group ID that the process uses, run (id $user) in your instance to see the id
          validRegex: /.{1,}/
        - id: $$cap_password
          label: Set the password for the results database.
        - id: $$cap_webui_port
          label: librespeed WebUI Port
          description: The port used to access librespeed
          defaultValue: '1853'
    instructions:
        start: >-
            Librespeed is a very lightweight Speedtest implemented in Javascript, using XMLHttpRequest and Web Workers. No Flash, No Java, No Websocket, No Bullshit.
        end: >-
            Aaaand you're done! 😄
            Your service is available at http://$$cap_appname.$$cap_root_domain
    displayName: 'Librespeed'
    isOfficial: true
    description: Librespeed is a very lightweight Speedtest implemented in Javascript, using XMLHttpRequest and Web Workers. No Flash, No Java, No Websocket, No Bullshit.
    documentation: Taken from https://github.com/librespeed/speedtest/wiki
